name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get tag name
        id: get-tag-name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get latest release tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        
      - name: Check tag values
        env:
          LATEST_TAG: ${{steps.latest-tag.outputs.tag}}
          SET_TAG: ${{steps.get-tag-name.outputs.VERSION}}
          IMAGE_TAG: "{% if 'heads' in $SET_TAG %} $LATEST_TAG {% else %} $SET_TAG {% endif %}"
        run: |
          echo $IMAGE_TAG
          echo ${{steps.latest-tag.outputs.tag}}
          echo ${{steps.get-tag-name.outputs.VERSION}}
