name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get tag name
        id: get-tag-name
        run: echo "TAG::${GITHUB_REF/refs\/tags\//" >> $GITHUB_ENV
        
      - name: Get branch for which workflow has been triggered
        id: get-branch
        run: echo "BRANCH=${GITHUB_REF/refs\/heads\//" >> $GITHUB_ENV

      - name: Get latest release tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        
      - name: Set default Image tag to be latest tag
        env:
          LATEST_TAG: ${{ steps.latest-tag.outputs.tag }}
        run: echo "IMAGE_TAG=$LATEST_TAG" >> $GITHUB_ENV
        
      - name: Set Image tag if triggered using branch
        if: contains( $TAG, 'heads')
        run: |
          echo "IMAGE_TAG=$BRANCH" >> $GITHUB_ENV
          
      - name: Set Image tag if triggered using tag
        if: contains( $BRANCH, 'tags')
        run: |
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
        
      - name: Check tag values
        env:
          LATEST_TAG: ${{ steps.latest-tag.outputs.tag }}
        run: |
          echo $LATEST_TAG
          echo $TAG
          echo $BRANCH
          echo $IMAGE_TAG
          
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check env vars exist
        run: |
          echo $LATEST_TAG
          echo $TAG
          echo $BRANCH
          echo $IMAGE_TAG
