# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get latest release tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        
      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.event.inputs.tag }} || ${{steps.latest-tag.outputs.tag}}
        run: |
          echo $IMAGE_TAG
          echo ${{ github.event.inputs.tag }}
          echo ${{steps.latest-tag.outputs.tag}}
          echo $VERSION
          echo ${{steps.get_tag_name.outputs.VERSION}}
          echo ${{steps.get_tag_name.outputs}}
