name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get latest release tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        
      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.event.inputs.tag }} || ${{steps.latest-tag.outputs.tag}} || ${{steps.get_tag_name.outputs.VERSION}}
        run: |
          echo $IMAGE_TAG
          echo ${{steps.latest-tag.outputs.tag}}
          echo ${{steps.get_tag_name.outputs.VERSION}}
